# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_initial"),
        ("reels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reelhashtag",
            name="hashtag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posts.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="reelhashtag",
            name="reel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reels.reel"
            ),
        ),
        migrations.AddField(
            model_name="reel",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True,
                related_name="reels",
                through="reels.ReelHashtag",
                to="posts.hashtag",
            ),
        ),
        migrations.AddField(
            model_name="reelview",
            name="reel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_records",
                to="reels.reel",
            ),
        ),
        migrations.AddField(
            model_name="reelview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reelhashtag",
            index=models.Index(
                fields=["hashtag", "-created_at"], name="reels_reelh_hashtag_ea83bc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reelhashtag",
            constraint=models.UniqueConstraint(
                fields=("reel", "hashtag"), name="reelhashtag_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["author", "-created_at"], name="reels_reel_author__615b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["is_hidden", "-created_at"],
                name="reels_reel_is_hidd_3d9e04_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reelview",
            constraint=models.UniqueConstraint(
                fields=("reel", "user"), name="reelview_unique"
            ),
        ),
    ]
