# Generated by Django 5.1.15 on 2026-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="sound",
            field=models.JSONField(
                blank=True,
                help_text="Song picked with Use sound (title, artist, preview).",
                null=True,
            ),
        ),
    ]
