# Generated by Django 5.1.15 on 2026-10-10 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_group_purpose"),
        ("messaging", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[("user", "Message"), ("system", "Group event")],
                default="user",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MessageHidden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_for",
                        to="messaging.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "message"],
                        name="messaging_m_user_id_db9cb8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user"), name="message_hidden_unique"
                    )
                ],
            },
        ),
    ]
