# Generated by Django 5.1.15 on 2026-10-10 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0004_post_sound"),
        ("reels", "0003_reel_sound"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("jamendo", "Jamendo"),
                            ("flashx", "Original sound"),
                            ("deezer", "Deezer preview (legacy)"),
                            ("itunes", "iTunes preview (legacy)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="Track id at the provider.", max_length=64
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(blank=True, max_length=200)),
                ("cover_url", models.URLField(blank=True, max_length=500)),
                ("audio_url", models.URLField(max_length=500)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=60)),
                ("license_name", models.CharField(blank=True, max_length=80)),
                ("license_url", models.URLField(blank=True, max_length=300)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Backlink to the track page (attribution).",
                        max_length=300,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sounds stay on old posts but can't be picked.",
                    ),
                ),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "origin_post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_sound",
                        to="posts.post",
                    ),
                ),
                (
                    "origin_reel",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_sound",
                        to="reels.reel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_sounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-uses_count", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["source", "is_active", "-uses_count"],
                        name="music_sound_source_aa321b_idx",
                    ),
                    models.Index(fields=["title"], name="music_sound_title_c58534_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="sound_source_external_unique",
                    )
                ],
            },
        ),
    ]
