# Generated by Django 5.1.15 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("query", "Query"),
                            ("user", "User"),
                            ("hashtag", "Hashtag"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
