# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyreaction",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storyreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="viewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["author", "expires_at"], name="stories_sto_author__b245e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyreaction",
            constraint=models.UniqueConstraint(
                fields=("story", "user"), name="storyreaction_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="storyview",
            index=models.Index(
                fields=["viewer", "story"], name="stories_sto_viewer__38ef06_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyview",
            constraint=models.UniqueConstraint(
                fields=("story", "viewer"), name="storyview_unique"
            ),
        ),
    ]
