# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("likes", "0002_initial"),
        ("reels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="reel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="reels.reel",
            ),
        ),
    ]
