# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("likes", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "-created_at"], name="likes_like_post_id_9d77cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["reel", "-created_at"], name="likes_like_reel_id_b6eba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["comment"], name="likes_like_comment_be6a12_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("comment__isnull", True),
                        ("post__isnull", False),
                        ("reel__isnull", True),
                    ),
                    models.Q(
                        ("comment__isnull", True),
                        ("post__isnull", True),
                        ("reel__isnull", False),
                    ),
                    models.Q(
                        ("comment__isnull", False),
                        ("post__isnull", True),
                        ("reel__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="like_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post"),
                name="like_unique_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reel__isnull", False)),
                fields=("user", "reel"),
                name="like_unique_reel",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("user", "comment"),
                name="like_unique_comment",
            ),
        ),
    ]
