# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saves", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saveditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="saveditem",
            index=models.Index(
                fields=["user", "-created_at"], name="saves_saved_user_id_c679c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="saveditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("reel__isnull", True)),
                    models.Q(("post__isnull", True), ("reel__isnull", False)),
                    _connector="OR",
                ),
                name="saved_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="saveditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post"),
                name="saved_unique_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="saveditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reel__isnull", False)),
                fields=("user", "reel"),
                name="saved_unique_reel",
            ),
        ),
    ]
