# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "parent_comment", "created_at"],
                name="comments_co_post_id_f93677_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["reel", "parent_comment", "created_at"],
                name="comments_co_reel_id_6f12b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment", "created_at"],
                name="comments_co_parent__15d1db_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("reel__isnull", True)),
                    models.Q(("post__isnull", True), ("reel__isnull", False)),
                    _connector="OR",
                ),
                name="comment_exactly_one_target",
            ),
        ),
    ]
