# Generated by Django 5.1.15 on 2026-10-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_password_reset_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_calls",
            field=models.BooleanField(
                default=True, help_text="People who follow each other can call."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="New followers need approval; posts are followers-only.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_prefs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="presence_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_activity_status",
            field=models.BooleanField(
                default=True,
                help_text="Others can see when this person is online or was last active.",
            ),
        ),
    ]
