# Generated by Django 5.1.15 on 2026-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser_name", models.CharField(max_length=80)),
                ("advertiser_logo_url", models.URLField(blank=True, max_length=500)),
                ("headline", models.CharField(max_length=90)),
                ("body", models.TextField(blank=True, max_length=500)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Filled automatically when you upload an image.",
                        max_length=500,
                    ),
                ),
                (
                    "image_public_id",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "link_url",
                    models.URLField(
                        help_text="Where the button sends people (https://...).",
                        max_length=500,
                    ),
                ),
                (
                    "call_to_action",
                    models.CharField(
                        choices=[
                            ("learn_more", "Learn more"),
                            ("shop_now", "Shop now"),
                            ("sign_up", "Sign up"),
                            ("download", "Download"),
                            ("book_now", "Book now"),
                            ("contact_us", "Contact us"),
                            ("order_now", "Order now"),
                            ("watch_more", "Watch more"),
                        ],
                        default="learn_more",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave empty to start now.", null=True
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to run until switched off.",
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Higher weight is shown more often (1-10)."
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0, editable=False)),
                ("clicks", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["is_active", "starts_at", "ends_at"],
                        name="ads_ad_is_acti_9bedd0_idx",
                    )
                ],
            },
        ),
    ]
