# Generated by Django 5.1.15 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("avatar", "Profile image"),
                            ("cover", "Cover image"),
                            ("post", "Post media"),
                            ("story", "Story media"),
                            ("reel", "Reel video"),
                            ("message", "Message attachment"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=8
                    ),
                ),
                ("public_id", models.CharField(max_length=255, unique=True)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("format", models.CharField(blank=True, max_length=16)),
                ("secure_url", models.URLField(max_length=500)),
                ("bytes", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Seconds, videos only.", null=True
                    ),
                ),
                ("is_attached", models.BooleanField(db_index=True, default=False)),
                ("attached_at", models.DateTimeField(blank=True, null=True)),
                ("is_managed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
