# Generated by Django 5.1.15 on 2026-10-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("avatar", "Profile image"),
                    ("cover", "Cover image"),
                    ("post", "Post media"),
                    ("story", "Story media"),
                    ("reel", "Reel video"),
                    ("message", "Message attachment"),
                    ("group", "Group photo"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
