# Generated by Django 5.1.15 on 2026-10-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0002_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.category",
            ),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="hashtag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posts.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="posts.PostHashtag",
                to="posts.hashtag",
            ),
        ),
        migrations.AddField(
            model_name="postmedia",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_media",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="tagged_in_posts",
                through="posts.PostTag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["hashtag", "-created_at"], name="posts_posth_hashtag_2ef953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["created_at"], name="posts_posth_created_7afe16_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="posthashtag",
            constraint=models.UniqueConstraint(
                fields=("post", "hashtag"), name="posthashtag_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="postmedia",
            constraint=models.UniqueConstraint(
                fields=("post", "order"), name="postmedia_unique_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="posttag",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="posttag_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="posts_post_author__f8ea20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at", "-id"], name="posts_post_created_a7e5d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "is_hidden", "-created_at"],
                name="posts_post_visibil_5a2ffd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category", "-created_at"], name="posts_post_categor_26d9c0_idx"
            ),
        ),
    ]
