# Generated by Django 5.1.15 on 2026-10-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="event_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="event_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="post",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("happy", "Happy"),
                    ("excited", "Excited"),
                    ("grateful", "Grateful"),
                    ("relaxed", "Relaxed"),
                    ("loved", "Loved"),
                    ("motivated", "Motivated"),
                    ("proud", "Proud"),
                    ("tired", "Tired"),
                    ("sad", "Sad"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="music_title",
            field=models.CharField(
                blank=True, help_text="Song label shown on the post.", max_length=120
            ),
        ),
    ]
