# Generated by Django 5.1.15 on 2026-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_event_starts_at_post_event_title_post_mood_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sound",
            field=models.JSONField(
                blank=True,
                help_text="Song picked with Use sound (title, artist, preview).",
                null=True,
            ),
        ),
    ]
