# Generated by Django 5.1.15 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("reply", "Comment reply"),
                            ("comment_like", "Comment like"),
                            ("follow", "Follow"),
                            ("mention", "Mention"),
                            ("tag", "Tagged in post"),
                            ("story_reaction", "Story reaction"),
                            ("story_reply", "Story reply"),
                            ("message", "Message"),
                            ("share", "Shared content"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("reel", "Reel"),
                            ("comment", "Comment"),
                            ("story", "Story"),
                            ("user", "User"),
                            ("conversation", "Conversation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Primary key of the target object.", max_length=64
                    ),
                ),
                ("preview", models.CharField(blank=True, max_length=160)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
