# Generated by Django 5.1.15 on 2026-10-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("reply", "Comment reply"),
                    ("comment_like", "Comment like"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("tag", "Tagged in post"),
                    ("story_reaction", "Story reaction"),
                    ("story_reply", "Story reply"),
                    ("message", "Message"),
                    ("share", "Shared content"),
                    ("live", "Went live"),
                    ("live_invite", "Live guest invite"),
                    ("group_add", "Added to a group"),
                    ("follow_request", "Follow request"),
                    ("follow_accepted", "Follow request accepted"),
                    ("missed_call", "Missed call"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("reel", "Reel"),
                    ("comment", "Comment"),
                    ("story", "Story"),
                    ("user", "User"),
                    ("conversation", "Conversation"),
                    ("live", "Live stream"),
                    ("call", "Call"),
                ],
                max_length=16,
            ),
        ),
    ]
